package initbin

import (
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"
)

// TestEmbeddedChecksums hashes the embedded blobs against the committed
// checksums.txt, catching a stale or hand-edited blob (in either state:
// committed stubs, or blobs regenerated by go generate).
func TestEmbeddedChecksums(t *testing.T) {
	want := map[string]string{}
	for _, line := range strings.Split(strings.TrimSpace(Checksums), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 2 {
			t.Fatalf("malformed checksums.txt line: %q", line)
		}
		want[fields[1]] = fields[0]
	}
	got := map[string][]byte{
		"moat-init-linux-amd64": BinaryFor("amd64"),
		"moat-init-linux-arm64": BinaryFor("arm64"),
	}
	if len(want) != len(got) {
		t.Fatalf("checksums.txt has %d entries, want %d", len(want), len(got))
	}
	for name, data := range got {
		sum := sha256.Sum256(data)
		if hex.EncodeToString(sum[:]) != want[name] {
			t.Errorf("%s: embedded bytes do not match checksums.txt — regenerate with 'go generate ./internal/initbin' (or restore stubs with 'make restore-init-stubs')", name)
		}
	}
}

func TestBinaryForArchSelection(t *testing.T) {
	if BinaryFor("amd64") == nil {
		t.Error("BinaryFor(amd64) = nil, want embedded blob")
	}
	if BinaryFor("arm64") == nil {
		t.Error("BinaryFor(arm64) = nil, want embedded blob")
	}
	// Companion: unsupported architectures yield nil, not a wrong-arch blob.
	if BinaryFor("riscv64") != nil {
		t.Error("BinaryFor(riscv64) != nil, want nil for unsupported arch")
	}
	if Binary() == nil {
		t.Error("Binary() = nil on a supported host arch")
	}
}

func TestIsStub(t *testing.T) {
	// The committed placeholders must be recognized as stubs so release
	// checks can refuse to ship them...
	if !IsStub([]byte("#!/bin/sh\n# moat-init-stub\necho FATAL >&2\nexit 1\n")) {
		t.Error("IsStub(stub content) = false, want true")
	}
	// ...and real binaries (ELF magic) must not be misclassified.
	if IsStub([]byte("\x7fELF\x02\x01\x01\x00moat-init")) {
		t.Error("IsStub(ELF bytes) = true, want false")
	}
	// Companion: an arbitrary shell script that is not the stub is not a stub.
	if IsStub([]byte("#!/bin/sh\necho hello\n")) {
		t.Error("IsStub(unrelated script) = true, want false")
	}
}

// TestCommittedBlobsAreStubs is the commit guard: the embed blobs tracked in
// git must be the fail-closed stubs, never the real cross-compiled binaries
// (which are ~2.5 MB build artifacts, not source). `go generate` overwrites
// them during a build; the build/test Makefile targets restore them
// afterward, so a clean checkout — and therefore CI and any commit — always
// carries stubs.
//
// This closes the gap TestEmbeddedChecksums leaves: that test only checks the
// blobs match checksums.txt, so a real binary committed together with its
// regenerated checksum passes it. This test fails on that state.
//
// If this fails locally, you have generated real binaries in your tree (e.g.
// via `make generate-init` or a bare `go generate`): run `make
// restore-init-stubs` before committing.
func TestCommittedBlobsAreStubs(t *testing.T) {
	for _, arch := range []string{"amd64", "arm64"} {
		if !IsStub(BinaryFor(arch)) {
			t.Errorf("embed/moat-init-linux-%s is a real binary, not the committed stub — run 'make restore-init-stubs' before committing (the real binaries are build artifacts, baked into ./moat at compile time, and must never be committed)", arch)
		}
	}
}

// TestStubFailsClosed pins the fail-closed contract of the committed stub:
// it must be a shell script that prints a FATAL message and exits 1, never
// a silent no-op that would start the user command as root.
func TestStubFailsClosed(t *testing.T) {
	for _, arch := range []string{"amd64", "arm64"} {
		b := BinaryFor(arch)
		if !IsStub(b) {
			t.Skipf("%s blob is a real binary (generated tree), stub contract not applicable", arch)
		}
		s := string(b)
		if !strings.Contains(s, "FATAL: moat-init stub embedded") {
			t.Errorf("%s stub missing FATAL message", arch)
		}
		if !strings.Contains(s, "exit 1") {
			t.Errorf("%s stub missing exit 1", arch)
		}
	}
}
